source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HYDateTools_Example', :exclusive => true do
  pod "HYDateTools", :path => "../"
end

target 'HYDateTools_Tests', :exclusive => true do
  pod "HYDateTools", :path => "../"

  
end
