source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HYDateTools_Example' do
  pod "HYDateTools", :path => "../"

  target 'HYDateTools_Tests' do
  pod "HYDateTools", :path => "../"
  end
end


